# Generated by Django 4.2.3 on 2023-08-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='sneakersapp.user',
        ),
    ]
