# Generated by Django 4.2.3 on 2023-08-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
