# Generated by Django 4.2.3 on 2023-08-01 01:41

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='sneakersapp.product',
        ),
    ]
